defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: lophyounee86
  host: localhost
  port: 5432
    
development: 
  database: unifa_development
  <<: *defaults 
  

test:  
  database: unifa_test 
  <<: *defaults   
